version: "4.0"

services:

  pubsub:
    image: messagebird/gcloud-pubsub-emulator:latest
    environment:
      - PUBSUB_PROJECT1=order-project,orders:order-subscription
    ports:
      - "8538:8681"

#  inventory-service:
#    build: inventory-service/
#    ports:
#      - "8082:8082"
#    depends_on:
#      - loki
#      - grafana
#      - tempo
#      - prometheus

#  fulfillment-service:
#    build: fulfillment-service/
#    ports:
#      - "8084:8084"
#    depends_on:
#      - loki
#      - grafana
#      - tempo
#      - prometheus

#  order-service:
#    build: order-service/
#    ports:
#      - "8080:8080"
#    depends_on:
#      - loki
#      - grafana
#      - tempo
#      - prometheus

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./monitoring/config/tempo-local.yml:/etc/tempo.yml
      - ./monitoring/data/tempo-data:/tmp/tempo
    ports:
      - "8000:8000" # tempo
      - "55681:55681" # otlp http

  loki:
    image: grafana/loki:latest
    command: [ "-config.file=/etc/loki/loki-config.yml" ]
    ports:
      - "3100:3100"                                   # loki needs to be exposed so it receives logs
    volumes:
      - ./monitoring/config/loki-local.yml:/etc/loki/loki-config.yml
      - ./monitoring/data/loki-data:/tmp/loki
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  prometheus:
    image: prom/prometheus:latest
    command: [ "--config.file=/etc/prometheus.yml" ]
    volumes:
      - ./monitoring/config/prometheus.yml:/etc/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./monitoring/config/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
