server:
  port: 8082
spring:
  application:
    name: inventory
  cloud:
    gcp:
      trace:
        pubsub:
          enabled: true
  zipkin:
    enabled: true
    sender:
      type: otlp
      otlp:
        endpoint: http://tempo:55681
logging:
  level:
    root: INFO
  com:
    ld:
      booster:
        example: DEBUG
booster:
  tasks:
    threads:
      settings:
        checkout:
          coreSize: 10
          maxSize: 20
          queueSize: 100
          prefix: checkout-tp-
        refill:
          coreSize: 10
          maxSize: 20
          queueSize: 100
          prefix: refill-tp-
